# Site settings
title: Spark Framework tutorials - Spark Java tutorials
description: > # > means to ignore newlines as long as indent is kept
  A collection of Spark Framework tutorials. Get started with learning Spark Framework today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sparktutorials.github.io" # the base hostname & protocol for your site
twitter_username: sparkjava
gems: [jekyll-redirect-from]

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

